Feature:Email Review

  Background:
    Given User is on nucomply page
   # Then verify login required screen is displayed
    When User click on login button
    Then user is redirected to login page
    When User enter following credentails
      | username               | password   |
      | Trupti.Natu@Nuarca.com | Trupti@123 |
    And User click on Logins Buttons
    Then log-ing is successful displayed
    And homepage is visible to user
    When user clicks on menu icon
    When User clicks on soutlion tab

  Scenario:TC-09 Verify that User can view the email review generated by uploading the doc/docx or pdf file
    When User clicks on email review tab
    Then verify email reiew screen is displayed
    When User enter following text in subject text field
      | subject | Compliance Review Request for New AI Implementation |
    Then verify the subject text is entered successfully
    When user  upload a email file
    Then verfiy the uploaded filename is displayed
    When user select all compliance concerns option
    Then verify all compliance concerns are selected
    When User click on review email button
    Then verify the output is generated successfully

  Scenario:TC-10 Verify that User can view the email review generated by entering body text
    When User clicks on email review tab
    Then verify email reiew screen is displayed
    When User enter following text in subject text field
      | subject | Compliance Review Request for New AI Implementation |
    Then verify the body text field and upload file option is displayed
    When User enter the body text from jsonfile "emailbody.json"
    Then verify the body text is entered successfully
    When user select all compliance concerns option
    Then verify all compliance concerns are selected
    When User click on review email button
    Then verify the output is generated successfully

  Scenario:TC-11 Verify that User can click on Reset button to reset each details selected and output text.
    When User clicks on email review tab
    Then verify email reiew screen is displayed
    When User enter following text in subject text field
      | subject | Compliance Review Request for New AI Implementation |
    Then verify the subject text is entered successfully
    When user  upload a email file
    When user select all compliance concerns option
    When User click on review email button
    Then verify the output is reset successfully


  Scenario:TC-12 Verify that User can click on Refresh Button Icon to clear the subject fields
    When User clicks on email review tab
    Then verify email reiew screen is displayed
    When User enter following text in subject text field
      | subject | Compliance Review Request for New AI Implementation |
    Then verify the subject text is entered successfully
    When User clicks on subject field refresh icon


  Scenario:TC-13 Verify that User can click on Refresh Button Icon to clear the body fields
    When User clicks on email review tab
    Then verify email reiew screen is displayed
    When User enter following text in subject text field
      | subject | Compliance Review Request for New AI Implementation |
    Then verify the subject text is entered successfully
    When User enter the body text from jsonfile "emailbody.json"
    Then verify the body text is entered successfully
    When User click on refresh icon of body text field

  Scenario: TC-14 Verify that User can click on Refresh Button Icon to clear selected details.Uploaded file
    When User clicks on email review tab
    Then verify email reiew screen is displayed
    When User enter following text in subject text field
      | subject | Compliance Review Request for New AI Implementation |
    Then verify the subject text is entered successfully
    When User upload a file
    #Then verfiy the uploaded filename is displayed
    When User click on refresh icon of upload file field
    Then verify the uploaded filename is cleared successfully








