@SolutionPolicyModule @smoke
Feature: Policy and Procedure Review

  Background:
    Given User is on nucomply page
    Then verify Login page is displayed
    When User click on login button
    Then user is redirected to login page
    When User enter following credentails
      | username               | password   |
      | Trupti.Natu@Nuarca.com | Trupti@123 |
    When User click on Logins Buttons
    Then log-ing is successful displayed
    Then homepage is visible to user
    When user clicks on menu icon


  Scenario: TC-20 Verify that User can view the policy review generated by uploading the doc/docx or pdf file
    When User clicks on soutlion tab
    And User clicks on Policy and Procedure review button
    Then verify policy review screen is displayed
    When User select policy as a document type from drop-down
    When User upload a file
    Then verify file is uploaded successfully
    When User select policy topics from drop-down
    Then verify policy topics are selected
    When User clicks on Review Policy button
    Then verify policy review is generated successfully


  Scenario: TC-21 Verfiy that user can download updated policy review file
    When User clicks on soutlion tab
    And User clicks on Policy and Procedure review button
    Then verify policy review screen is displayed
    When User select policy as a document type from drop-down
    Then verify policy option is selected
    When User upload a file
    Then verify file is uploaded successfully
    When User select policy topics from drop-down
    Then verify policy topics are selected
    When User clicks on Review Policy button
    Then verify policy review is generated successfully
    When user click on updated policy downlaodble link on policy output screen

  Scenario: TC-22 verify that user can download  redline policy review file
    When User clicks on soutlion tabs
    And User clicks on Policy and Procedure review button
    Then verify policy review screen is displayed
    When User select policy as a document type from drop-down
    When User upload a file
    Then verify file is uploaded successfully
    And User select policy topics from drop-down
    When User clicks on Review Policy button
    Then verify policy review is generated successfully
    When click on genrated redline downloadble procedure link on procedure output screen

