Feature:Marketing Review

  Background:
    Given User is on nucomply page
  # Then verify login required screen is displayed
    When User click on login button
    Then user is redirected to login page
    When User enter following credentails
      | username               | password   |
      | Trupti.Natu@Nuarca.com | Trupti@123 |
    When User click on Logins Buttons
    Then log-ing is successful displayed
    And homepage is visible to user
    When user clicks on menu icon
    When User clicks on soutlion tab


  Scenario:TC-15 Verify that User can view the marketing review generated by entering the body text
    When User clicks on marketing review tab
    Then verify marketing review screen is displayed
    When User enter a text from jsonfile "marketingbody.json" in body text field
    Then verify the marketing body text is entered successfully
    When User click on review Marketing Button
    Then verify the marekting review output is generated successfully

  Scenario:TC-16 Verify that User can view the marketing review generated by uploading the doc/docx or pdf file
    When User clicks on marketing review tab
    Then verify marketing review screen is displayed
    When User upload a marketing file
    Then verify the uploaded marketing filename is displayed
    When User click on review Marketing Button
    Then verify the marekting review output is generated successfully

  Scenario:TC-17 Verify that User can click on Reset button to reset the details selected and output text.
    When User clicks on marketing review tab
    Then verify marketing review screen is displayed
    When User upload a marketing file
    Then verify the uploaded marketing filename is displayed
    When User click on review Marketing Button
    Then verify the  marketing output is reset successfully

  Scenario:TC-18 Verify that User can click on Refresh Button Icon to clear body text
    When User clicks on marketing review tab
    Then verify marketing review screen is displayed
    When User enter a text from jsonfile "marketingbody.json" in body text field
    Then verify the marketing body text is entered successfully
    When User clicks on body text refresh icon
    Then verify the body text field is cleared successfully

  Scenario: TC-19 Verify that User can click on Refresh Button Icon to clear selected and Uploaded File
    When User clicks on marketing review tab
    Then verify marketing review screen is displayed
    When User upload a marketing file
    Then verify the uploaded marketing filename is displayed
    When User clicks on refresh icon of upload file
    Then verify the uploaded file is cleared successfully