Feature: Procedure Review

  Background:
    Given User is on nucomply page
    When User click on login button
    When User enter following credentails
      | username               | password   |
      | Trupti.Natu@Nuarca.com | Trupti@123 |
    When User click on Logins Buttons
    Then verify login popup is displayed
    When user clicks on menu icon


  Scenario:TC-45 Verify that User can view the procedure review generated by uploading the doc/docx or pdf file
    When User clicks on soutlion tab
    And User clicks on Policy and Procedure review option
    Then verify policy review screen is displayed
    When User select procedure as a document type from drop-down
    When user upload file
    Then verify file is procedure file is uploaded successfully
    When user select procedure topic
    Then verify procedure topic is selected
    When user clicks on review procedure button
    Then verify procedure review is generated successfully

  Scenario:TC-46 verify that user can download updated procedure review file
    When User clicks on soutlion tab
    And User clicks on Policy and Procedure review option
    Then verify policy review screen is displayed
    When User select procedure as a document type from drop-down
    #Then verify procedure option is selected
    When user upload file
    Then verify file is procedure file is uploaded successfully
    When user select procedure topic
    Then verify procedure topic is selected
    When user clicks on review procedure button
    Then verify procedure review is generated successfully
    When click on genrated updated procedure link on procedure output screen

  Scenario:TC-47 verify that user can download updated redline procedure review file
    When User clicks on soutlion tab
    When User clicks on Policy and Procedure review button
    Then verify policy review screen is displayed
    When User select procedure as a document type from drop-down
    #Then verify procedure option is selected
    When user upload file
    Then verify file is procedure file is uploaded successfully
    When user select procedure topic
    Then verify procedure topic is selected
    When user clicks on review procedure button
    When click on genrated redline procedure link on procedure output screen

  Scenario:TC-48 verify that after procedure output user is able to copy text
    When User clicks on soutlion tab
    When User clicks on Policy and Procedure review button
    Then verify policy review screen is displayed
    When User select procedure as a document type from drop-down
    #Then verify procedure option is selected
    When user upload file
    Then verify file is procedure file is uploaded successfully
    When user select procedure topic
    Then verify procedure topic is selected
    When user clicks on review procedure button
    Then verify procedure review is generated successfully

  Scenario:TC-49 verify that user is able to reset the procedure review details by clicking on reset button
    When User clicks on soutlion tab
    When User clicks on Policy and Procedure review button
    Then verify policy review screen is displayed
    When User select procedure as a document type from drop-down
    #Then verify procedure option is selected
    When user upload file
    Then verify file is procedure file is uploaded successfully
    When user select procedure topic
    Then verify procedure topic is selected
    When user clicks on review procedure button
    Then verify procedure review is generated successfully
